/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Control.C_SignUp;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author DELL
 */
public class V_SignUp extends javax.swing.JFrame {

    /**
     * Creates new form V_SignUp
     */
    public V_SignUp() {
        initComponents();
        
        txt_username.addFocusListener(new FocusAdapter() {
    @Override
    public void focusLost(FocusEvent e) {
        validateUsername();
    }
});
        txt_firstname.addFocusListener(new FocusAdapter() {
    @Override
    public void focusLost(FocusEvent e) {
        validateFirstName();
    }
});
        txt_lastname.addFocusListener(new FocusAdapter() {
    @Override
    public void focusLost(FocusEvent e) {
        validateLastName();
    }
});
        txt_password.addFocusListener(new FocusAdapter() {
    @Override
    public void focusLost(FocusEvent e) {
        validatePassword();
    }
});
    txt_telNo.addFocusListener(new FocusAdapter() {
    @Override
    public void focusLost(FocusEvent e) {
        validateTelNo();
    }
});    
    txt_txtAge.addFocusListener(new FocusAdapter() {
    @Override
    public void focusLost(FocusEvent e) {
        validateAge();
    }
});
          
    }
    private void validateUsername() {
        String username = txt_username.getText();
        if (username.isEmpty()) {
            lbl_username_error.setText("Username cannot be empty.");
        } else if (!username.matches("^[a-zA-Z]+$")) {
            lbl_username_error.setText("Username cannot contain numbers or special characters.");
        } else {
            lbl_username_error.setText(""); // Clear error message if validation passes
        }
    }
    private void validateFirstName() {
    String firstName = txt_firstname.getText();
    if (firstName.isEmpty()) {
        lbl_fnameerror.setText("First name cannot be empty.");
    }
    else if (!firstName.matches("^[a-zA-Z]+$")) {
            lbl_fnameerror.setText("First Name cannot contain numbers or special characters.");}
    else {
        lbl_fnameerror.setText("");
    }
}
private void validateLastName() {
    String lastName = txt_lastname.getText();
    if (lastName.isEmpty()) {
        lbl_lnameerror.setText("Last name cannot be empty.");
    } 
    else if (!lastName.matches("^[a-zA-Z]+$")) {
            lbl_lnameerror.setText("Last Name cannot contain numbers or special characters.");}
    else {
        lbl_lnameerror.setText("");
    }
}
private void validatePassword() {
    String password = txt_password.getText();
    if (password.isEmpty()) {
        lbl_passworderror.setText("Password cannot be empty.");
    } else if (password.length() < 6) {
        lbl_passworderror.setText("Password must be at least 6 characters long.");
    } else {
        lbl_passworderror.setText(""); // Clear error message if validation passes
    }
}
private void validateTelNo() {
    String telNoText = txt_telNo.getText();
    if (telNoText.isEmpty()) {
        lbl_tnoerror.setText("Telephone number cannot be empty.");
    } else {
        try {
            int telNo = Integer.parseInt(telNoText);
            if (telNo < 0) {
                lbl_tnoerror.setText("Telephone number cannot be negative.");
            } else if (telNoText.length() != 10) {
                lbl_tnoerror.setText("Telephone number must have exactly 10 digits.");
            } else {
                lbl_tnoerror.setText("");
            }
        } catch (NumberFormatException e) {
            lbl_tnoerror.setText("Invalid input for telephone number.");
        }
    }
}
private void validateAge() {
    String ageText = txt_txtAge.getText();
    if (ageText.isEmpty()) {
        lbl_ageerror.setText("Age cannot be empty.");
    } else {
        try {
            int age = Integer.parseInt(ageText);
            if (age < 0) {
                lbl_ageerror.setText("Age cannot be negative.");
            } else {
                lbl_ageerror.setText("");
            }
        } catch (NumberFormatException e) {
            lbl_ageerror.setText("Invalid input for age.");
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_lastname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_txtAge = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmb_dietpreferences = new javax.swing.JComboBox<>();
        cmb_dietrestrion = new javax.swing.JComboBox<>();
        txt_telNo = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_continue = new javax.swing.JButton();
        lbl_username_error = new javax.swing.JLabel();
        lbl_fnameerror = new javax.swing.JLabel();
        lbl_lnameerror = new javax.swing.JLabel();
        lbl_passworderror = new javax.swing.JLabel();
        lbl_tnoerror = new javax.swing.JLabel();
        lbl_ageerror = new javax.swing.JLabel();
        cbox_showpass = new javax.swing.JCheckBox();
        txt_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Sign Up");

        txt_firstname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_firstname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name");

        txt_lastname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_lastname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Age");

        txt_txtAge.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_txtAge.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telephone No");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Diet Preferences");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Diet Restriction");

        cmb_dietpreferences.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High-Protein Diet", "Balanced Diet", "Plant-Based Diet" }));

        cmb_dietrestrion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vegetarian", "Low-Sodium Diet", "Lactose-Free Diet" }));

        txt_telNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_save.setBackground(new java.awt.Color(0, 153, 204));
        btn_save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_continue.setBackground(new java.awt.Color(255, 255, 255));
        btn_continue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_continue.setForeground(new java.awt.Color(0, 153, 204));
        btn_continue.setText("Continue");
        btn_continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_continueActionPerformed(evt);
            }
        });

        lbl_username_error.setBackground(new java.awt.Color(255, 255, 255));
        lbl_username_error.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_username_error.setForeground(new java.awt.Color(255, 0, 51));

        lbl_fnameerror.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_fnameerror.setForeground(new java.awt.Color(255, 0, 0));

        lbl_lnameerror.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_lnameerror.setForeground(new java.awt.Color(255, 51, 51));

        lbl_passworderror.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_passworderror.setForeground(new java.awt.Color(255, 0, 0));

        lbl_tnoerror.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_tnoerror.setForeground(new java.awt.Color(255, 0, 0));

        lbl_ageerror.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_ageerror.setForeground(new java.awt.Color(255, 0, 0));

        cbox_showpass.setText("Show Password");
        cbox_showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_showpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(109, 109, 109)
                                    .addComponent(btn_save)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                    .addComponent(btn_continue)
                                    .addGap(51, 51, 51))
                                .addComponent(cmb_dietpreferences, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmb_dietrestrion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_txtAge))
                            .addComponent(txt_telNo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_ageerror, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbox_showpass))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_tnoerror, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                .addComponent(txt_firstname)
                                .addComponent(txt_lastname))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_username_error, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_fnameerror, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_passworderror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_lnameerror, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(19, 19, 19)
                        .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_username_error, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lbl_fnameerror, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_lnameerror, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_passworderror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cbox_showpass)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_tnoerror, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_telNo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_ageerror, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_dietpreferences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_dietrestrion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_continue)
                            .addComponent(btn_save))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
      
       try {
        String username = txt_username.getText();
        String f_name = txt_firstname.getText();
        String l_name = txt_lastname.getText();
        String password = txt_password.getText();
        int tno = Integer.parseInt(txt_telNo.getText());
        int age = Integer.parseInt(txt_txtAge.getText());
        String diet_prefer = (String) cmb_dietpreferences.getSelectedItem();
        String diet_restrict = (String) cmb_dietrestrion.getSelectedItem();

        // Check for empty fields (you can customize these checks)
        if (username.isEmpty() || f_name.isEmpty() || l_name.isEmpty() || password.isEmpty() || diet_prefer.isEmpty() || diet_restrict.isEmpty()) {
            // Handle the case of empty fields, e.g., display an error message
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        } else {
            // All data is valid, proceed with the signup process
            C_SignUp c1 = new C_SignUp();
            c1.signUpUser(username, f_name, l_name, password, tno, age, diet_prefer, diet_restrict);
        }
    } catch (NumberFormatException e) {
        // Handle the case where parsing to an integer fails (e.g., non-numeric input)
        JOptionPane.showMessageDialog(this, "Please check all the fields again.");
    }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_continueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_continueActionPerformed
        hide();
        V_Home h1=new V_Home();
        h1.setVisible(true);
    }//GEN-LAST:event_btn_continueActionPerformed

    private void cbox_showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_showpassActionPerformed
        if (cbox_showpass.isSelected()) {
        txt_password.setEchoChar((char) 0); // Show characters as plain text
    } else {
        txt_password.setEchoChar('*'); // Hide characters with '*'
    }
    }//GEN-LAST:event_cbox_showpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_continue;
    private javax.swing.JButton btn_save;
    private javax.swing.JCheckBox cbox_showpass;
    private javax.swing.JComboBox<String> cmb_dietpreferences;
    private javax.swing.JComboBox<String> cmb_dietrestrion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ageerror;
    private javax.swing.JLabel lbl_fnameerror;
    private javax.swing.JLabel lbl_lnameerror;
    private javax.swing.JLabel lbl_passworderror;
    private javax.swing.JLabel lbl_tnoerror;
    private javax.swing.JLabel lbl_username_error;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_telNo;
    private javax.swing.JTextField txt_txtAge;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
